# environment.yml
name: multimodal
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # Core scientific Computing
  - numpy
  - pandas
  - scipy

  # Machine learning
  - scikit-learn

  # Medical images processing
  - pydicom
  - simpleitk
  - scikit-image
  - nibabel

  # Visualization
  - matplotlib
  - seaborn
